ALTER TABLE students ADD COLUMN IF NOT EXISTS application_no VARCHAR(100) UNIQUE;
ALTER TABLE students ADD COLUMN IF NOT EXISTS dob DATE;
ALTER TABLE students ADD COLUMN IF NOT EXISTS is_first_login BOOLEAN DEFAULT true;
